# Generated by Django 3.2.7 on 2022-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/upload/')),
                ('price', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('V', 'Vegetables'), ('NV', 'Non-Vegetables')], max_length=20)),
            ],
        ),
    ]
