# Generated by Django 3.2.7 on 2022-02-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_branch_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='App.manager'),
        ),
    ]
