# Generated by Django 3.2.7 on 2022-02-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_order_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
